version: '3.5'

services:
  mysql:
     image: mariadb
     container_name: ${DOMAIN}-mysql
     restart: unless-stopped
     volumes:
        - ./${DOMAIN}-mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     ports:
        - "${MYSQL_PORT}:3306"

  wordpress:
     depends_on:
       - mysql
     container_name: ${DOMAIN}-wordpress
     image: wordpress
     restart: unless-stopped
     volumes:
       - ${WP_PATH}/${DOMAIN}:/var/www/html
       - ./conf.d/uploadsize.ini:/usr/local/etc/php/conf.d/uploadsize.ini
     environment:
       WORDPRESS_DB_HOST: ${DOMAIN}-mysql:${MYSQL_PORT}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
       VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
       LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}
       LETSENCRYPT_EMAIL: ${EMAIL}
       WP_ENV: ${WP_ENV}
     logging:
       options:
         max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}
     ports:
       - "${IP:-0.0.0.0}:${PORT}:80"

  wpcli:
    image: tatemz/wp-cli
    container_name: ${DOMAIN}-${WP_CLI:-wp-cli}
    volumes:
      - ${WP_PATH}/${DOMAIN}:/var/www/html
    depends_on:
      - mysql
    entrypoint: wp

  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${DOMAIN}-${NGINX:-nginx}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:80:80"
      - "${IP:-0.0.0.0}:443:443"
    volumes:
      - ./${DOMAIN}-nginx/conf.d:/etc/nginx/conf.d
      - ./${DOMAIN}-nginx/vhost.d:/etc/nginx/vhost.d
      - ./${DOMAIN}-nginx/html:/usr/share/nginx/html
      - ./${DOMAIN}-nginx/certs:/etc/nginx/certs:ro
      - ./${DOMAIN}-nginx/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_LOG_MAX_FILE:-10}

  docker-gen:
    image: jwilder/docker-gen:0.7.3
    command: -notify-sighup ${DOMAIN}-${NGINX:-nginx} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOMAIN}-${DOCKER_GEN:-docker-gen}
    restart: always
    volumes:
      - ./${DOMAIN}-nginx/conf.d:/etc/nginx/conf.d
      - ./${DOMAIN}-nginx/vhost.d:/etc/nginx/vhost.d
      - ./${DOMAIN}-nginx/html:/usr/share/nginx/html
      - ./${DOMAIN}-nginx/certs:/etc/nginx/certs:ro
      - ./${DOMAIN}-nginx/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${DOCKER_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${DOCKER_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${DOCKER_GEN_LOG_MAX_FILE:-10}

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9.1
    container_name: ${DOMAIN}-${LETS_ENCRYPT:-letsencrypt}
    restart: always
    volumes:
      - ./${DOMAIN}-nginx/conf.d:/etc/nginx/conf.d
      - ./${DOMAIN}-nginx/vhost.d:/etc/nginx/vhost.d
      - ./${DOMAIN}-nginx/html:/usr/share/nginx/html
      - ./${DOMAIN}-nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOMAIN}-${DOCKER_GEN:-docker-gen}
      NGINX_PROXY_CONTAINER: ${DOMAIN}-${NGINX:-nginx}
    logging:
      driver: ${LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: ${LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${LETSENCRYPT_LOG_MAX_FILE:-10}