version: '3.5'

services:
  mysql:
     image: mariadb
     container_name: mysql
     restart: unless-stopped
     volumes:
        - mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     ports:
        - "${MYSQL_PORT}:3306"

  wordpress:
     depends_on:
       - mysql
     container_name: wordpress
     image: wordpress
     restart: unless-stopped
     volumes:
       - ../${PROJECT_NAME}:/var/www/html
       - ./conf.d/uploadsize.ini:/usr/local/etc/php/conf.d/uploadsize.ini
     environment:
       WORDPRESS_DB_HOST: mysql:${MYSQL_PORT}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${EMAIL}
       WP_ENV: ${WP_ENV}
     logging:
       options:
         max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}
     ports:
       - "${IP:-0.0.0.0}:${PORT}:80"

#   wpcli:
#     image: tatemz/wp-cli
#     volumes:
#       - ../${PROJECT_NAME}:/var/www/html
#     depends_on:
#       - mysql
#     entrypoint: wp

  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX:-nginx}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:80:80"
      - "${IP:-0.0.0.0}:443:443"
    volumes:
      - ${NGINX_FILES_PATH:-./nginx}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./nginx}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./nginx}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./nginx}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./nginx}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX:-nginx} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./nginx}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./nginx}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./nginx}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./nginx}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./nginx}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./nginx}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./nginx}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./nginx}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./nginx}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX:-nginx}
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

volumes:
  mysql:
    name: ${PROJECT_NAME}-mysql